spring:
  datasource:
    # 数据库配置 使用 DruidDat 驱动
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://155.94.145.131:3306/SpringMysqlTest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: wjp
    password: summerwen15091427.cc
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: Select 1
      name: MyPool
  application:
    name: MysqlDruid
server:
  port: 8081